### ISSUE TITLE
Invalid syntax in line 2368

### ISSUE THREAD

**Issue by ralphwetzel** [fgallaire/wsgiserver#3]
Hi!
I thought to give your server a try - yet it failed to work in an Python 3.5.2 environment.
The error statement says: 'Invalid syntax in line 2368'.
Most probably it is due to the fact that you use code that is not valid in Python 3 (and the PY2 guard you introduced doesn't cover the invalid syntax!)
This could be fixed by using something like six.reraise().
Greetings, Ralph

**Comment by fgallaire** [comment]
Thanks for the bug report, I will fix it as soon as possible.
